#!/bin/sh
cd /home
mkdir -p /var/run/celery
mkdir -p /var/log/celery
python db/create.py
touch /var/log/celery/log.log
celery -A api.access.contest worker -l info --loglevel=DEBUG &
export TESTING=1
#python test/test_app.py
export TESTING=0
if [[ "$BUILD" = "prod" ]]; then
    gunicorn --worker-class eventlet -p app.pid -w 3 app:contestplatform -b :9000
else 
   python appdev.py 
fi

