#!/bin/sh
pip install -r requirement.txt
python test/test_app.py
failtest=$?
if [[ $failtest != 0 ]]; then
    echo "Test failed!"
    exit $failtest
fi
#redeploy the app without downtime
# checks if pid file exist since app is being started with pid file
if [[ -f app.pid ]];then
    pid=$(cat app.pid) 
    kill -HUP $pid
fi