#!/bin/sh
pip install -r requirement.txt
python test/test_app.py
failtest=$?
if [[ $failtest != 0 ]]; then
    echo "Test failed!"
    exit $failtest
fi
#redeploy the app without downtime
pkill -HUP gunicorn